"""Shared range and threshold policy for integrations telemetry and SLO evaluation."""

TELEMETRY_DAYS_MIN = 1
TELEMETRY_DAYS_MAX = 30

TELEMETRY_SUMMARY_LIMIT_MIN = 50
TELEMETRY_SUMMARY_LIMIT_MAX = 5000

SLO_QUERY_LIMIT_MIN = 100
SLO_QUERY_LIMIT_MAX = 5000

PERCENT_THRESHOLD_MIN = 0.0
PERCENT_THRESHOLD_MAX = 100.0

DEFAULT_MAX_ERROR_RATE_PCT = 5.0
DEFAULT_MIN_SCHEMA_V2_PCT = 95.0
SAMPLE_THRESHOLD_MIN = 1
SAMPLE_THRESHOLD_MAX = 5000
DEFAULT_MIN_SCHEMA_V2_SAMPLE_COUNT = 25
