#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

PYTHON_BIN="${PYTHON_BIN:-$ROOT_DIR/.venv311/bin/python}"

"$PYTHON_BIN" -m pytest -q \
  backend/tests/test_connector_endpoint_smoke.py \
  backend/tests/test_connector_normalization.py \
  backend/tests/test_connector_orchestration_unittest.py \
  backend/tests/test_integration_health_and_webhook.py \
  backend/tests/test_integration_http_contract.py \
  backend/tests/test_telemetry_status_filter_workflow_contract.py \
  backend/tests/test_telemetry_status_count_workflow_contract.py \
  backend/tests/test_telemetry_quality_workflow_contract.py \
  backend/tests/test_telemetry_export_distribution_smoke.py \
  backend/tests/test_telemetry_status_count_posture_unittest.py \
  backend/tests/test_sales_integrations_chain_contract.py \
  backend/tests/test_sales_backend_chain_contract.py \
  backend/tests/test_sales_intelligence_chain_contract.py \
  backend/tests/test_governance_recommended_commands_unittest.py \
  backend/tests/test_governance_export_endpoint_contract.py \
  backend/tests/test_governance_weekly_report_endpoint_contract.py \
  backend/tests/test_integration_logging_contract.py \
  backend/tests/test_integration_telemetry_summary.py \
  backend/tests/test_integrations_reliability_unittest.py \
  backend/tests/test_integrations_reliability_runbook_contract.py \
  backend/tests/test_connector_alert_response_matrix_contract.py \
  backend/tests/test_connector_slo_alerts_contract.py \
  backend/tests/test_connector_slo_script_query_unittest.py \
  backend/tests/test_integration_slo_policy_contract.py \
  backend/tests/test_connector_release_gate_smoke.py \
  backend/tests/test_connector_release_gate_result_contract.py \
  backend/tests/test_database_index_contract.py \
  backend/tests/test_backfill_integration_telemetry_event_root_contract_unittest.py \
  backend/tests/test_integration_telemetry_event_root_backfill_policy_unittest.py \
  backend/tests/test_integration_telemetry_event_root_backfill_guarded_apply_unittest.py \
  backend/tests/test_integration_telemetry_event_root_backfill_artifact_contract_unittest.py \
  backend/tests/test_generate_integration_telemetry_event_root_backfill_artifact_fixtures_unittest.py \
  backend/tests/test_integration_telemetry_event_root_backfill_artifact_fixture_workflow_contract.py \
  backend/tests/test_integration_telemetry_event_root_backfill_artifact_retention_unittest.py \
  backend/tests/test_cleanup_integration_telemetry_event_root_backfill_artifacts_unittest.py \
  backend/tests/test_integration_telemetry_event_root_backfill_artifact_cleanup_policy_unittest.py \
  backend/tests/test_integration_telemetry_event_root_backfill_artifact_cleanup_guarded_apply_unittest.py \
  backend/tests/test_telemetry_event_root_backfill_artifact_cleanup_workflow_contract.py \
  backend/tests/test_telemetry_event_root_backfill_workflow_contract.py \
  backend/tests/test_baseline_metrics_tooling_unittest.py \
  backend/tests/test_baseline_metrics_artifact_contract_unittest.py \
  backend/tests/test_generate_baseline_metrics_artifact_fixtures_unittest.py \
  backend/tests/test_validate_baseline_metrics_artifact_retention_unittest.py \
  backend/tests/test_cleanup_baseline_metrics_artifacts_unittest.py \
  backend/tests/test_baseline_metrics_artifact_cleanup_policy_unittest.py \
  backend/tests/test_baseline_metrics_artifact_cleanup_guarded_apply_unittest.py \
  backend/tests/test_baseline_metrics_artifact_fixture_workflow_contract.py \
  backend/tests/test_baseline_metrics_artifact_workflow_contract.py \
  backend/tests/test_connector_release_gate_artifact_fixture_unittest.py \
  backend/tests/test_connector_release_gate_artifact_contract_unittest.py \
  backend/tests/test_validate_connector_release_gate_artifact_retention_unittest.py \
  backend/tests/test_cleanup_connector_release_gate_artifacts_unittest.py \
  backend/tests/test_connector_release_gate_artifact_cleanup_policy_unittest.py \
  backend/tests/test_connector_release_gate_artifact_cleanup_guarded_apply_unittest.py \
  backend/tests/test_connector_release_gate_artifact_fixture_workflow_contract.py \
  backend/tests/test_connector_telemetry_snapshot_fixture_unittest.py \
  backend/tests/test_connector_telemetry_snapshot_contract_unittest.py \
  backend/tests/test_connector_telemetry_snapshot_retention_unittest.py \
  backend/tests/test_connector_governance_weekly_report_tooling_unittest.py \
  backend/tests/test_generate_governance_packet_fixture_unittest.py \
  backend/tests/test_connector_governance_weekly_report_contract_unittest.py \
  backend/tests/test_connector_governance_weekly_report_retention_unittest.py \
  backend/tests/test_connector_governance_weekly_cleanup_policy_unittest.py \
  backend/tests/test_connector_governance_weekly_cleanup_guarded_apply_unittest.py \
  backend/tests/test_cleanup_connector_governance_weekly_reports_unittest.py \
  backend/tests/test_governance_weekly_report_smoke.py \
  backend/tests/test_governance_packet_status_normalization_smoke.py \
  backend/tests/test_governance_packet_runtime_prereqs_smoke.py \
  backend/tests/test_governance_schema_parity_smoke.py \
  backend/tests/test_governance_snapshot_parity_smoke.py \
  backend/tests/test_governance_export_failure_smoke.py \
  backend/tests/test_governance_history_retention_smoke.py \
  backend/tests/test_telemetry_packet_filter_smoke.py \
  backend/tests/test_cleanup_connector_telemetry_snapshots_unittest.py \
  backend/tests/test_connector_telemetry_cleanup_policy_unittest.py \
  backend/tests/test_connector_telemetry_cleanup_guarded_apply_unittest.py \
  backend/tests/test_traceability_ci_failure_smoke.py \
  backend/tests/test_traceability_governance_handoff_smoke.py \
  backend/tests/test_baseline_governance_drift_smoke.py \
  backend/tests/test_baseline_quick_workflow_contract.py \
  backend/tests/test_verify_sales_baseline_command_aliases_unittest.py \
  backend/tests/test_baseline_command_aliases_workflow_contract.py \
  backend/tests/test_validate_sales_baseline_command_aliases_artifact_unittest.py \
  backend/tests/test_generate_sales_baseline_command_aliases_artifact_fixtures_unittest.py \
  backend/tests/test_baseline_command_aliases_artifact_fixture_workflow_contract.py \
  backend/tests/test_validate_sales_baseline_command_aliases_artifact_retention_unittest.py \
  backend/tests/test_cleanup_sales_baseline_command_aliases_artifacts_unittest.py \
  backend/tests/test_sales_baseline_command_aliases_artifact_cleanup_policy_unittest.py \
  backend/tests/test_sales_baseline_command_aliases_artifact_cleanup_guarded_apply_unittest.py \
  backend/tests/test_baseline_command_aliases_artifact_workflow_contract.py \
  backend/tests/test_baseline_command_chain_contract.py \
  backend/tests/test_verify_sales_runtime_prereqs_unittest.py \
  backend/tests/test_validate_sales_runtime_prereqs_artifact_unittest.py \
  backend/tests/test_validate_sales_runtime_prereqs_artifact_retention_unittest.py \
  backend/tests/test_cleanup_sales_runtime_prereqs_artifacts_unittest.py \
  backend/tests/test_sales_runtime_prereqs_artifact_cleanup_policy_unittest.py \
  backend/tests/test_sales_runtime_prereqs_artifact_cleanup_guarded_apply_unittest.py \
  backend/tests/test_generate_sales_runtime_prereqs_artifact_fixtures_unittest.py \
  backend/tests/test_sales_runtime_prereqs_artifact_fixture_workflow_contract.py \
  backend/tests/test_sales_runtime_prereqs_artifact_workflow_contract.py \
  backend/tests/test_dev_setup_contract.py \
  backend/tests/test_frontend_sales_smoke_workflow_contract.py \
  backend/tests/test_frontend_sales_workflow_contract.py \
  backend/tests/test_sales_dashboard_smoke_workflow_contract.py \
  backend/tests/test_sales_dashboard_workflow_contract.py \
  backend/tests/test_multi_channel_controls_workflow_contract.py \
  backend/tests/test_sales_smoke_workflow_contract.py \
  backend/tests/test_baseline_orchestration_remediation_workflow_contract.py \
  backend/tests/test_connector_canary_dry_run_workflow_contract.py \
  backend/tests/test_connector_credential_lifecycle_workflow_contract.py \
  backend/tests/test_connector_orchestration_workflow_contract.py \
  backend/tests/test_connector_provider_lookups_workflow_contract.py \
  backend/tests/test_connector_lookups_workflow_contract.py \
  backend/tests/test_connector_reliability_workflow_contract.py \
  backend/tests/test_connector_input_validation_workflow_contract.py \
  backend/tests/test_connector_lookups_ui_workflow_contract.py \
  backend/tests/test_connector_lookups_export_workflow_contract.py \
  backend/tests/test_sendgrid_reliability_workflow_contract.py \
  backend/tests/test_credential_freshness_workflow_contract.py \
  backend/tests/test_sales_campaign_workflow_contract.py \
  backend/tests/test_schema_gate_workflow_contract.py \
  backend/tests/test_orchestration_slo_gate_workflow_contract.py \
  backend/tests/test_connector_release_gate_workflow_contract.py \
  backend/tests/test_governance_report_workflow_contract.py \
  backend/tests/test_governance_export_guard_workflow_contract.py \
  backend/tests/test_governance_history_retention_workflow_contract.py \
  backend/tests/test_governance_connector_pressure_workflow_contract.py \
  backend/tests/test_governance_duplicate_artifact_remediation_workflow_contract.py \
  backend/tests/test_governance_schema_ui_workflow_contract.py \
  backend/tests/test_telemetry_packet_filter_workflow_contract.py \
  backend/tests/test_telemetry_export_distribution_workflow_contract.py \
  backend/tests/test_traceability_ci_guard_workflow_contract.py \
  backend/tests/test_traceability_governance_handoff_workflow_contract.py \
  backend/tests/test_baseline_governance_drift_workflow_contract.py \
  backend/tests/test_workflow_contracts_workflow_contract.py \
  backend/tests/test_health_workflow_contract.py \
  backend/tests/test_smoke_workflow_contract_coverage.py \
  backend/tests/test_provider_contract_fixtures.py \
  backend/tests/test_real_integrations_resilience.py \
  backend/tests/test_retry_resilience_unittest.py \
  backend/tests/test_connector_canary_dry_run_smoke.py \
  backend/tests/test_connector_canary_evidence_runbook_contract.py \
  backend/tests/test_connector_runbook_contract.py \
  backend/tests/test_runbook_path_normalization_contract.py \
  backend/tests/test_connector_release_signoff_runbook_contract.py \
  backend/tests/test_signoff_toolchain_unittest.py \
  backend/tests/test_validate_connector_signoff_bundle_unittest.py \
  backend/tests/test_generate_governance_packet_validation_artifact_fixtures_unittest.py \
  backend/tests/test_validate_governance_packet_validation_artifact_unittest.py \
  backend/tests/test_validate_governance_packet_validation_artifact_retention_unittest.py \
  backend/tests/test_cleanup_governance_packet_validation_artifacts_unittest.py \
  backend/tests/test_governance_packet_validation_artifact_cleanup_policy_unittest.py \
  backend/tests/test_governance_packet_validation_artifact_cleanup_guarded_apply_unittest.py \
  backend/tests/test_governance_packet_artifact_fixture_workflow_contract.py \
  backend/tests/test_validate_governance_packet_artifacts_unittest.py \
  backend/tests/test_governance_packet_workflow_contract.py \
  backend/tests/test_governance_schema_endpoint_workflow_contract.py \
  backend/tests/test_enforce_connector_release_gate_unittest.py
