from pathlib import Path


RUNBOOK_PATH = (
    Path(__file__).resolve().parents[2]
    / "docs"
    / "runbooks"
    / "INTEGRATIONS_RELIABILITY_RUNBOOK.md"
)


def _runbook_text() -> str:
    return RUNBOOK_PATH.read_text(encoding="utf-8")


def test_integrations_reliability_runbook_exists():
    assert RUNBOOK_PATH.exists()


def test_integrations_reliability_runbook_includes_schema_tracking_fields():
    content = _runbook_text()
    required_fragments = [
        "bySchemaVersion",
        "salesIntelligence.bySchemaVersion",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_recent_event_correlation_fields():
    content = _runbook_text()
    required_fragments = [
        "recentEvents",
        "requestId",
        "schemaVersion",
        "traceabilityDecision",
        "governanceStatus",
        "governancePacketValidationStatus",
        "governancePacketValidationWithinFreshness",
        "retryFinalOutcome",
        "retryRetryable",
        "retryErrorType",
        "retryErrorStatusCode",
        "retryErrorReasonCode",
        "connectorRateLimitEndpoint",
        "connectorRateLimitRetryAfterSeconds",
        "connectorRateLimitResetInSeconds",
        "connectorRateLimitWindowSeconds",
        "connectorRateLimitMaxRequests",
        "connectorValidationProvider",
        "connectorValidationEndpoint",
        "connectorValidationField",
        "connectorValidationReason",
        "connectorValidationErrorCode",
        "connectorValidationReceived",
        "connectorValidationMinimum",
        "connectorValidationMaximum",
        "governanceSchemaReasonCodeParityOk",
        "governanceSchemaRecommendedCommandParityOk",
        "governanceSchemaHandoffParityOk",
        "governanceSchemaAllParityOk",
        "governanceSchemaRolloutBlocked",
        "governanceSchemaReasonCodeCount",
        "governanceSchemaRecommendedCommandCount",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_telemetry_status_and_correlation_index_inventory():
    content = _runbook_text()
    required_fragments = [
        "integration_telemetry(userId, governanceStatus, createdAt desc)",
        "integration_telemetry(userId, governancePacketValidationStatus, createdAt desc)",
        "integration_telemetry(userId, requestId, createdAt desc)",
        "integration_telemetry(userId, schemaVersion, createdAt desc)",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_schema_slo_gate_fields():
    content = _runbook_text()
    required_fragments = [
        "/api/integrations/integrations/telemetry/slo-gates",
        "/api/integrations/integrations/telemetry/governance-report",
        "/api/integrations/integrations/telemetry/governance-report/export",
        "/api/integrations/integrations/telemetry/governance-report/history",
        "/api/integrations/integrations/telemetry/governance-schema",
        "/api/integrations/integrations/telemetry/snapshot-governance",
        "/api/integrations/integrations/telemetry/baseline-governance",
        "schemaCoverage.thresholdPct",
        "schemaCoverage.observedPct",
        "schemaCoverage.minSampleCount",
        "gates.schemaCoveragePassed",
        "gates.schemaSampleSizePassed",
        "retryAudit.maxEventCountThreshold",
        "retryAudit.observedEventCount",
        "retryAudit.maxAvgNextDelaySecondsThreshold",
        "retryAudit.observedAvgNextDelaySeconds",
        "retryAudit.observedMaxNextDelaySeconds",
        "gates.retryAuditVolumePassed",
        "gates.retryAuditDelayPassed",
        "orchestrationAudit.maxAttemptErrorCountThreshold",
        "orchestrationAudit.observedAttemptErrorCount",
        "orchestrationAudit.maxAttemptSkippedCountThreshold",
        "orchestrationAudit.observedAttemptSkippedCount",
        "gates.orchestrationAttemptErrorPassed",
        "gates.orchestrationAttemptSkippedPassed",
        "orchestrationGate.available",
        "orchestrationGate.decision",
        "orchestrationGate.attemptErrorGatePassed",
        "orchestrationGate.attemptSkippedGatePassed",
        "orchestrationGate.maxAttemptErrorCountThreshold",
        "orchestrationGate.observedAttemptErrorCount",
        "orchestrationGate.maxAttemptSkippedCountThreshold",
        "orchestrationGate.observedAttemptSkippedCount",
        "min_schema_v2_pct=95&min_schema_v2_sample_count=25&max_orchestration_attempt_error_count=5&max_orchestration_attempt_skipped_count=25",
        "schemaContractParity.reasonCodeCount",
        "schemaContractParity.recommendedCommandCount",
        "schemaContractParity.reasonCodeParity.topLevelVsRolloutActions",
        "schemaContractParity.reasonCodeParity.topLevelVsExportActions",
        "schemaContractParity.reasonCodeParity.topLevelVsExportAlerts",
        "schemaContractParity.reasonCodeParity.topLevelVsExportReasonCodes",
        "schemaContractParity.recommendedCommandParity.topLevelVsExport",
        "schemaContractParity.handoffParity.rolloutBlockedMatchesExport",
        "schemaContractParity.handoffParity.ownerRoleMatchesExport",
        "schemaContractParity.handoffParity.handoffActionsMatchRolloutActions",
        "schemaContractParity.handoffParity.handoffActionCount",
        "schemaContractParity.handoffParity.rolloutActionCount",
        "schemaContractParity.computedAt",
        "reason_code_parity_ok",
        "recommended_command_parity_ok",
        "handoff_parity_ok",
        "governanceSchemaAudit.eventCount",
        "governanceSchemaAudit.statusCounts",
        "governanceSchemaAudit.reasonCodeParityPassCount",
        "governanceSchemaAudit.reasonCodeParityFailCount",
        "governanceSchemaAudit.recommendedCommandParityPassCount",
        "governanceSchemaAudit.recommendedCommandParityFailCount",
        "governanceSchemaAudit.handoffParityPassCount",
        "governanceSchemaAudit.handoffParityFailCount",
        "governanceSchemaAudit.allParityPassedCount",
        "governanceSchemaAudit.allParityFailedCount",
        "governanceSchemaAudit.rolloutBlockedCount",
        "governanceSchemaAudit.latestEvaluatedAt",
        "Governance Schema Audits",
        "Governance Schema Audit Status",
        "Parity posture: PASS",
        "Schema Parity Status: PASS",
        "Failed checks:",
        "values are normalized status tokens (`A-Z0-9` with `_` separators)",
        "counted as `UNKNOWN` in `packetValidationAudit.statusCounts`",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_schema_gate_smoke_command():
    content = _runbook_text()
    assert "npm run verify:smoke:schema-gate" in content


def test_integrations_reliability_runbook_includes_orchestration_slo_smoke_command():
    content = _runbook_text()
    assert "npm run verify:smoke:orchestration-slo-gate" in content


def test_integrations_reliability_runbook_includes_release_gate_smoke_command():
    content = _runbook_text()
    assert "npm run verify:smoke:release-gate" in content


def test_integrations_reliability_runbook_includes_full_baseline_command():
    content = _runbook_text()
    assert "npm run verify:baseline" in content


def test_integrations_reliability_runbook_includes_required_command_inventory():
    content = _runbook_text()
    required_commands = [
        "npm run verify:ci:sales",
        "npm run verify:ci:sales:extended",
        "npm run verify:baseline:runtime-prereqs",
        "npm run verify:baseline:command-aliases",
        "npm run verify:baseline:command-aliases:artifact",
        "npm run verify:baseline:command-aliases:artifact:contract",
        "npm run verify:baseline:command-aliases:artifact:retention",
        "npm run verify:baseline:command-aliases:artifact:fixtures",
        "npm run verify:baseline:command-aliases:artifact:cleanup:dry-run",
        "npm run verify:baseline:command-aliases:artifact:cleanup:policy",
        "npm run verify:baseline:command-aliases:artifact:cleanup:apply:guarded",
        "npm run verify:baseline:runtime-prereqs:artifact",
        "npm run verify:baseline:runtime-prereqs:artifact:contract",
        "npm run verify:baseline:runtime-prereqs:artifact:retention",
        "npm run verify:baseline:runtime-prereqs:artifact:fixtures",
        "npm run verify:baseline:runtime-prereqs:artifact:cleanup:dry-run",
        "npm run verify:baseline:runtime-prereqs:artifact:cleanup:policy",
        "npm run verify:baseline:runtime-prereqs:artifact:cleanup:apply:guarded",
        "npm run test",
        "npm run typecheck",
        "npm run verify:baseline:metrics",
        "npm run verify:baseline:metrics:artifact",
        "npm run verify:baseline:metrics:artifact:contract",
        "npm run verify:baseline:metrics:artifact:retention",
        "npm run verify:baseline:metrics:artifact:fixtures",
        "npm run verify:baseline:metrics:artifact:cleanup:dry-run",
        "npm run verify:baseline:metrics:artifact:cleanup:policy",
        "npm run verify:baseline:metrics:artifact:cleanup:apply:guarded",
        "npm run verify:baseline:quick",
        "npm run verify:baseline:metrics:contract",
        "npm run verify:release-gate:artifact:contract",
        "npm run verify:release-gate:artifact:fixtures",
        "npm run verify:release-gate:artifact:retention",
        "npm run verify:release-gate:artifact:cleanup:dry-run",
        "npm run verify:release-gate:artifact:cleanup:policy",
        "npm run verify:release-gate:artifact:cleanup:apply:guarded",
        "npm run verify:telemetry:traceability:fixture",
        "npm run verify:telemetry:traceability:contract",
        "npm run verify:telemetry:traceability:retention",
        "npm run verify:telemetry:traceability:cleanup:dry-run",
        "npm run verify:telemetry:traceability:cleanup:policy",
        "npm run verify:telemetry:traceability:cleanup:apply:guarded",
        "npm run verify:telemetry:event-root:backfill:dry-run",
        "npm run verify:telemetry:event-root:backfill:policy",
        "npm run verify:telemetry:event-root:backfill:apply:guarded",
        "npm run verify:telemetry:event-root:backfill:artifact:contract",
        "npm run verify:telemetry:event-root:backfill:artifact:fixtures",
        "npm run verify:telemetry:event-root:backfill:artifact:retention",
        "npm run verify:telemetry:event-root:backfill:artifact:cleanup:dry-run",
        "npm run verify:telemetry:event-root:backfill:artifact:cleanup:policy",
        "npm run verify:telemetry:event-root:backfill:artifact:cleanup:apply:guarded",
        "npm run verify:telemetry:traceability",
        "npm run verify:governance:weekly:report",
        "npm run verify:governance:weekly:report:contract",
        "npm run verify:governance:weekly:endpoint:contract",
        "npm run verify:governance:packet:fixture",
        "npm run verify:governance:packet:validate",
        "npm run verify:governance:packet:contract",
        "npm run verify:governance:packet:artifact:fixtures",
        "npm run verify:governance:packet:artifact:retention",
        "npm run verify:governance:packet:artifact:cleanup:dry-run",
        "npm run verify:governance:packet:artifact:cleanup:policy",
        "npm run verify:governance:packet:artifact:cleanup:apply:guarded",
        "npm run verify:governance:schema:preflight",
        "npm run verify:governance:weekly:retention",
        "npm run verify:governance:weekly:cleanup:dry-run",
        "npm run verify:governance:weekly:cleanup:policy",
        "npm run verify:governance:weekly:cleanup:apply:guarded",
        "npm run verify:governance:weekly",
        "npm run verify:smoke:governance-report",
        "npm run verify:smoke:governance-export-guard",
        "npm run verify:smoke:governance-schema-endpoint",
        "npm run verify:smoke:governance-history-retention",
        "npm run verify:smoke:governance-connector-pressure",
        "npm run verify:smoke:governance-duplicate-artifact-remediation",
        "npm run verify:smoke:governance-schema-ui",
        "npm run verify:smoke:runtime-prereqs-artifact",
        "npm run verify:smoke:baseline-metrics-artifact",
        "npm run verify:smoke:governance-packet",
        "npm run verify:smoke:telemetry-packet-filter",
        "npm run verify:smoke:telemetry-quality",
        "npm run verify:smoke:telemetry-status-filter",
        "npm run verify:smoke:telemetry-status-counts",
        "npm run verify:smoke:telemetry-event-root-backfill",
        "npm run verify:smoke:telemetry-event-root-backfill-artifact-cleanup",
        "npm run verify:smoke:telemetry-export-distribution",
        "npm run verify:smoke:frontend-sales",
        "npm run verify:smoke:multi-channel-controls",
        "npm run verify:smoke:baseline-command-aliases",
        "npm run verify:smoke:baseline-command-aliases-artifact",
        "npm run verify:smoke:traceability-ci-guard",
        "npm run verify:smoke:traceability-governance-handoff",
        "npm run verify:smoke:baseline-governance-drift",
        "npm run verify:smoke:baseline-orchestration-remediation",
        "npm run verify:backend:sales:integrations",
        "npm run verify:auth:integrations:contracts",
        "npm run verify:backend:sales:intelligence",
        "npm run verify:backend:sales",
        "npm run verify:docs:sales:connectors",
        "npm run verify:docs:sales",
        "npm run verify:smoke:campaign",
        "npm run verify:smoke:canary-dry-run",
        "npm run verify:smoke:credential-lifecycle",
        "npm run verify:smoke:connector-reliability",
        "npm run verify:smoke:connector-orchestration",
        "npm run verify:smoke:connector-provider-lookups",
        "npm run verify:smoke:connector-lookups",
        "npm run verify:smoke:connector-lookups-ui",
        "npm run verify:smoke:connector-lookups-export",
        "npm run verify:smoke:connector-input-validation",
        "npm run verify:smoke:sendgrid-reliability",
        "npm run verify:smoke:credential-freshness",
        "npm run verify:smoke:schema-gate",
        "npm run verify:smoke:orchestration-slo-gate",
        "npm run verify:smoke:release-gate",
        "npm run verify:smoke:sales",
        "npm run verify:smoke:workflow-contracts",
    ]
    for command in required_commands:
        assert command in content


def test_integrations_reliability_runbook_documents_backfill_apply_env_gate():
    content = _runbook_text()
    assert "BACKFILL_ALLOW_APPLY=true" in content
    assert "BASELINE_COMMAND_ALIASES_ARTIFACT_CLEANUP_ALLOW_APPLY=true" in content
    assert "RUNTIME_PREREQS_ARTIFACT_CLEANUP_ALLOW_APPLY=true" in content
    assert "RELEASE_GATE_ARTIFACT_CLEANUP_ALLOW_APPLY=true" in content
    assert "GOVERNANCE_PACKET_ARTIFACT_CLEANUP_ALLOW_APPLY=true" in content


def test_integrations_reliability_runbook_includes_connector_lookup_export_validation_steps():
    content = _runbook_text()
    required_fragments = [
        "npm run verify:smoke:connector-lookups-export",
        "Export Company Lookup JSON",
        "Export Apollo Lookup JSON",
        "exportSchemaVersion",
        "exportGeneratedAt",
        "exportType",
        "selectedProvider",
        "providerOrder",
        "provider rate-limit metadata fields",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_sendgrid_reliability_observability_fields():
    content = _runbook_text()
    required_fragments = [
        "missingSendIdForUpdate",
        "unknownEventTypeCount",
        "invalidTimestampCount",
        "timestampFallbackCount",
        "futureSkewEventCount",
        "staleEventCount",
        "freshEventCount",
        "timestampFallbackEventTypeCounts",
        "eventTypeCounts.unknown",
        "timestampPressureLabel",
        "timestampPressureHint",
        "timestampAnomalyCount",
        "timestampAnomalyRatePct",
        "timestampAnomalyEventTypeCounts",
        "timestampDominantAnomalyBucket",
        "timestampDominantAnomalyBucketCount",
        "timestampDominantAnomalyEventType",
        "timestampDominantAnomalyEventTypeCount",
        "timestampPressureHighAnomalyRatePct",
        "timestampPressureModerateAnomalyRatePct",
        "timestampPressureHighAnomalyCount",
        "timestampPressureModerateAnomalyCount",
        "updateEligibleEventCount",
        "updateEligibleEventTypeCounts",
        "unsupportedEventTypeCount",
        "unsupportedEventTypeCounts",
        "emailUpdateEventTypeCounts",
        "missingSendIdByEventType",
        "deduplicatedEventTypeCounts",
        "futureSkewEventTypeCounts",
        "staleEventTypeCounts",
        "timestampAgeBucketCounts",
        "futureSkewThresholdSeconds",
        "staleEventAgeThresholdSeconds",
        "integrations_connector_credential_saved",
        "integrations_connector_credential_removed",
        "integrations_connector_rate_limited",
        "integrations_connector_input_validation_failed",
        "integrations_retry_fail_fast",
        "integrations_retry_exhausted",
        "Retry-After",
        "X-RateLimit-Limit",
        "X-RateLimit-Remaining",
        "X-RateLimit-Window-Seconds",
        "X-RateLimit-Reset-In-Seconds",
        "X-RateLimit-Reset-At",
        "detail.errorCode=connector_rate_limited",
        "detail.retryAfterSeconds",
        "detail.rateLimit.limit",
        "detail.rateLimit.remaining",
        "detail.rateLimit.windowSeconds",
        "detail.rateLimit.resetInSeconds",
        "rateLimit.resetAt",
        "rateLimit.resetInSeconds",
        "connectorLifecycle.eventCount",
        "connectorLifecycle.byAction",
        "connectorLifecycle.byProvider",
        "retryAudit.eventCount",
        "retryAudit.byOperation",
        "retryAudit.byProvider",
        "retryAudit.maxNextDelaySeconds",
        "retryAudit.avgNextDelaySeconds",
        "retryAudit.latestEventAt",
        "exportRetryTerminalEventCount",
        "exportRetryTerminalOutcomeCounts",
        "exportRetryTerminalRetryabilityCounts",
        "exportRetryTerminalErrorTypeCounts",
        "exportRetryTerminalReasonCodeCounts",
        "exportRetryTerminalStatusCodeCounts",
        "exportRetryTerminalPressureLabel",
        "exportRetryTerminalPressureHint",
        "exportRetryTerminalPressureSignalCount",
        "exportRetryTerminalTopOutcome",
        "exportRetryTerminalTopReasonCode",
        "exportRetryTerminalTopStatusCode",
        "orchestrationAudit.eventCount",
        "orchestrationAudit.attemptStatusCounts",
        "orchestrationAudit.reasonCodeCounts",
        "orchestrationAudit.maxAttemptCount",
        "orchestrationAudit.avgAttemptCount",
        "orchestrationAudit.maxLatencyMs",
        "orchestrationAudit.avgLatencyMs",
        "orchestrationAudit.trendByDay",
        "connectorRateLimit.eventCount",
        "connectorRateLimit.byEndpoint",
        "connectorRateLimit.latestEventAt",
        "connectorRateLimit.maxRetryAfterSeconds",
        "connectorRateLimit.avgRetryAfterSeconds",
        "connectorRateLimit.maxResetInSeconds",
        "connectorRateLimit.avgResetInSeconds",
        "sendgridWebhookTimestamp.eventCount",
        "sendgridWebhookTimestamp.pressureLabelCounts",
        "sendgridWebhookTimestamp.pressureHintCounts",
        "sendgridWebhookTimestamp.timestampFallbackCount",
        "sendgridWebhookTimestamp.futureSkewEventCount",
        "sendgridWebhookTimestamp.staleEventCount",
        "sendgridWebhookTimestamp.freshEventCount",
        "sendgridWebhookTimestamp.timestampAnomalyCountTotal",
        "sendgridWebhookTimestamp.avgTimestampAnomalyRatePct",
        "sendgridWebhookTimestamp.maxTimestampAnomalyRatePct",
        "sendgridWebhookTimestamp.timestampAgeBucketCounts",
        "sendgridWebhookTimestamp.timestampAnomalyEventTypeCounts",
        "sendgridWebhookTimestamp.timestampDominantAnomalyBucketCounts",
        "sendgridWebhookTimestamp.timestampDominantAnomalyEventTypeCounts",
        "sendgridWebhookTimestamp.latestEventAt",
        "recentEvents[].timestampPressureLabel",
        "recentEvents[].timestampPressureHint",
        "recentEvents[].timestampAnomalyCount",
        "recentEvents[].timestampAnomalyRatePct",
        "recentEvents[].timestampAnomalyEventTypeCounts",
        "recentEvents[].timestampDominantAnomalyBucket",
        "recentEvents[].timestampDominantAnomalyEventType",
        "recentEvents[].timestampAgeBucketCounts",
        "recentEvents[].futureSkewThresholdSeconds",
        "recentEvents[].staleEventAgeThresholdSeconds",
        "connectorValidation.eventCount",
        "connectorValidation.byEndpoint",
        "connectorValidation.byProvider",
        "connectorValidation.byField",
        "connectorValidation.byReason",
        "connectorValidation.latestEventAt",
        "Connector Input-Validation Audits",
        "Connector Input-Validation Posture",
        "`High`: `maxRetryAfterSeconds >= 45` or `avgResetInSeconds >= 45`",
        "`Moderate`: `20 <= maxRetryAfterSeconds < 45` or `20 <= avgResetInSeconds < 45`",
        "`Low`: below moderate thresholds",
        "connector input-validation failures exceed 5 events in 10 minutes",
        "connector input-validation failures exceed 2% of connector lookup requests over 15 minutes",
        "actionableUnhealthyProviders",
        "credentialActionRequiredProviders",
        "credentialFreshnessStatusCounts",
        "credentialFreshnessStatusCountsSource",
        "credentialFreshnessStatusCountsMismatch",
        "credentialFreshnessStatusCountsServer",
        "credentialFreshnessStatusCountsFallback",
        "credentialFreshnessByProvider",
        "credentialFreshnessActionRequiredCount",
        "credentialFreshnessWithinPolicyCount",
        "credentialFreshnessUnknownCount",
        "credentialConfiguredMaxAgeDays",
        "credentialRotationMaxAgeDays",
        "Connector Credential Freshness",
        "Health Status",
        "Healthy/Unhealthy",
        "Freshness ACTION_REQUIRED",
        "Freshness READY/UNKNOWN",
        "Freshness status-count source: server|local.",
        "Credential freshness status-count mismatch",
        "No connector freshness telemetry yet.",
        "healthyCount",
        "unhealthyCount",
        "recommendedCommands",
        "recommendedCommandCount",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_credential_freshness_incident_response():
    content = _runbook_text()
    required_fragments = [
        "Credential Freshness Incident Response",
        "status=ACTION_REQUIRED",
        "credentialActionRequiredProviders",
        "credentialFreshnessActionRequiredCount",
        "credentialFreshnessStatusCounts",
        "credentialFreshnessStatusCountsSource",
        "credentialFreshnessStatusCountsMismatch",
        "credentialFreshnessStatusCountsServer",
        "credentialFreshnessStatusCountsFallback",
        "credentialFreshnessByProvider",
        "credentialStaleReasons",
        "POST /api/integrations/integrations/{provider}",
        "npm run verify:smoke:credential-freshness",
        "npm run verify:smoke:connector-reliability",
        "npm run verify:smoke:connector-provider-lookups",
        "npm run verify:smoke:connector-lookups",
        "npm run verify:smoke:connector-lookups-ui",
        "npm run verify:smoke:connector-lookups-export",
        "npm run verify:smoke:sendgrid-reliability",
        "status=READY",
        "credentialFreshnessActionRequiredCount=0",
        "credentialActionRequiredProviders=[]",
        "credentialStale=false",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_traceability_audit_summary_fields():
    content = _runbook_text()
    required_fragments = [
        "traceabilityAudit.eventCount",
        "traceabilityAudit.decisionCounts",
        "traceabilityAudit.readyCount",
        "traceabilityAudit.notReadyCount",
        "packetValidationAudit.eventCount",
        "packetValidationAudit.statusCounts",
        "packetValidationAudit.withinFreshnessCount",
        "packetValidationAudit.outsideFreshnessCount",
        "packetValidationAudit.missingFreshnessCount",
        "schemaMetadata.activeVersion",
        "schemaMetadata.source",
        "schemaMetadata.override.isSet",
        "schemaMetadata.override.isValid",
        "reasonCodes",
        "reasonCodeCount",
        "recommendedCommands",
        "recommendedCommandCount",
        "governanceExport.reasonCodes",
        "governanceExport.reasonCodeCount",
        "governanceExport.recommendedCommands",
        "governanceExport.recommendedCommandCount",
        "governanceExport.alerts[].reasonCode",
        "connectorRateLimit.pressure.label",
        "governanceExport.connectorRateLimit.pressure.label",
        "connectorPressureParity.eventCountMatchesNested",
        "connectorPressureParity.eventCountMatchesTotals",
        "connectorPressureParity.byEndpointMatchesNested",
        "connectorPressureParity.pressureLabelMatchesNested",
        "sendgridWebhookTimestamp.eventCount",
        "sendgridWebhookTimestamp.timestampAnomalyCountTotal",
        "governanceExport.sendgridWebhookTimestamp.eventCount",
        "governanceExport.sendgridWebhookTimestamp.timestampAnomalyCountTotal",
        "sendgridWebhookTimestampParity.eventCountMatchesNested",
        "sendgridWebhookTimestampParity.eventCountMatchesTotals",
        "sendgridWebhookTimestampParity.anomalyCountTotalMatchesNested",
        "sendgridWebhookTimestampParity.anomalyCountTotalMatchesTotals",
        "sendgridWebhookTimestampParity.pressureLabelCountsMatchNested",
        "sendgridWebhookTimestampParity.latestEventAtMatchesNested",
        "totals.sendgridWebhookTimestampEventCount",
        "totals.sendgridWebhookTimestampAnomalyCountTotal",
        "totals.connectorRateLimitEventCount",
        "schemaVersionCounts",
        "duplicateArtifactNames",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_recent_event_filter_and_export_context_fields():
    content = _runbook_text()
    required_fragments = [
        "packet_only_recent_events=true",
        "packet_only_recent_events=false",
        "governance_status=ACTION_REQUIRED",
        "packet_validation_status=READY",
        "packet_only_recent_events=true&packet_validation_status=READY",
        "recentEventsFilter",
        "recentEventsFilter=all",
        "recentEventsGovernanceStatusFilter",
        "recentEventsPacketValidationStatusFilter",
        "recentEventsTotalCount",
        "recentEventsFilteredCount",
        "recentEventsPacketValidationCount",
        "recentEventsNonPacketCount",
        "recentEventsGovernanceStatusCounts",
        "recentEventsPacketValidationStatusCounts",
        "recentEventsGovernanceStatusCountsSource",
        "recentEventsPacketValidationStatusCountsSource",
        "recentEventsGovernanceStatusCountsMismatch",
        "recentEventsPacketValidationStatusCountsMismatch",
        "recentEventsGovernanceStatusCountsServer",
        "recentEventsPacketValidationStatusCountsServer",
        "recentEventsGovernanceStatusCountsFallback",
        "recentEventsPacketValidationStatusCountsFallback",
        "recentEventsGovernanceStatusCountsPosture",
        "recentEventsPacketValidationStatusCountsPosture",
        "recentEventsGovernanceStatusCountsPostureSeverity",
        "recentEventsPacketValidationStatusCountsPostureSeverity",
        "recentEventsGovernanceStatusCountsRequiresInvestigation",
        "recentEventsPacketValidationStatusCountsRequiresInvestigation",
        "Telemetry status-count provenance interpretation matrix:",
        "source=server, mismatch=false",
        "source=server, mismatch=true",
        "source=local, mismatch=false",
        "source=local, mismatch=true",
        "backend forced local fallback but preserved drift evidence",
        "When backend posture metadata is present (`recentEvents...CountsPosture*`), UI posture chips and export posture fields should match backend metadata exactly.",
        "If backend posture tokens are invalid/unsupported, posture chips and export posture fields must fall back to computed source+mismatch posture defaults.",
        "Status-count posture • Governance: SERVER_CONSISTENT|SERVER_DRIFT|LOCAL_FALLBACK|LOCAL_DRIFT • Packet: SERVER_CONSISTENT|SERVER_DRIFT|LOCAL_FALLBACK|LOCAL_DRIFT.",
        "Export parity for provenance matrix:",
        "exportRecentEventsGovernanceStatusCountsSource",
        "exportRecentEventsPacketValidationStatusCountsSource",
        "exportRecentEventsGovernanceStatusCountsMismatch",
        "exportRecentEventsPacketValidationStatusCountsMismatch",
        "exportRecentEventsGovernanceStatusCountsServer",
        "exportRecentEventsPacketValidationStatusCountsServer",
        "exportRecentEventsGovernanceStatusCountsFallback",
        "exportRecentEventsPacketValidationStatusCountsFallback",
        "exportRecentEventsGovernanceStatusCountsPosture",
        "exportRecentEventsPacketValidationStatusCountsPosture",
        "exportRecentEventsGovernanceStatusCountsPostureSeverity",
        "exportRecentEventsPacketValidationStatusCountsPostureSeverity",
        "exportRecentEventsGovernanceStatusCountsRequiresInvestigation",
        "exportRecentEventsPacketValidationStatusCountsRequiresInvestigation",
        "governance_status` / `packet_validation_status` must be non-empty status tokens",
        "supported `recentEventsFilter` values are `all` and `packet`",
        "fall back to local operator-selected filter",
        "if `recentEventsTotalCount` or `recentEventsFilteredCount` is malformed",
        "Showing X of Y recent events.",
        "when server-applied `recentEventsFilter` differs from selected UI filter",
        "exported `exportRecentEventsFilter` matches server-applied filter",
        "No packet-validation events in this telemetry window.",
        "Increase Window Days or Event Limit",
        "exportRequestedWindowDays",
        "exportRequestedLimit",
        "exportSchemaVersion",
        "exportRecentEventsFilter",
        "exportRecentEventsSelectedFilter",
        "exportRecentEventsServerFilter",
        "exportRecentEventsServerFilterRaw",
        "exportRecentEventsServerFilterRawTrimmed",
        "exportRecentEventsServerFilterBlank",
        "exportRecentEventsServerFilterUnsupported",
        "exportRecentEventsServerFilterEvaluation",
        "exportRecentEventsServerFilterNormalizationChanged",
        "exportRecentEventsFilterMismatch",
        "exportRecentEventsFilterSource",
        "exportRecentEventsFilterResolution",
        "should be `server` when response echoes a supported filter token",
        "local_blank_server_filter",
        "should be `true` when `exportRecentEventsServerFilterRaw` exists",
        "trims to an empty token",
        "should be `supported`, `unsupported`, or `absent`",
        "required casing/whitespace normalization",
        "exportRecentEventsDisplayedCount",
        "exportRecentEventsTotalCount",
        "exportRecentEventsPacketValidationCount",
        "exportRecentEventsNonPacketCount",
        "exportRecentEventsGovernanceStatusCounts",
        "exportRecentEventsPacketValidationStatusCounts",
        "exportConnectorValidationEventCount",
        "exportConnectorValidationLatestEventAt",
        "exportConnectorValidationEndpointCount",
        "exportConnectorValidationProviderCount",
        "exportConnectorValidationFieldCount",
        "exportConnectorValidationReasonCount",
        "exportRetryAuditEventCount",
        "exportRetryAuditLatestEventAt",
        "exportRetryAuditMaxNextDelaySeconds",
        "exportRetryAuditAvgNextDelaySeconds",
        "exportRetryAuditOperationCount",
        "exportRetryAuditProviderCount",
        "exportIntegrationHealthStatus",
        "exportIntegrationHealthGeneratedAt",
        "exportIntegrationHealthHealthyCount",
        "exportIntegrationHealthUnhealthyCount",
        "exportIntegrationHealthActionableUnhealthyProviders",
        "exportIntegrationHealthCredentialActionRequiredProviders",
        "exportIntegrationHealthCredentialConfiguredMaxAgeDays",
        "exportIntegrationHealthCredentialRotationMaxAgeDays",
        "exportIntegrationHealthCredentialFreshnessStatusCounts",
        "exportIntegrationHealthCredentialFreshnessByProvider",
        "exportIntegrationHealthCredentialFreshnessTotalProviders",
        "exportIntegrationHealthCredentialFreshnessActionRequiredCount",
        "exportIntegrationHealthCredentialFreshnessWithinPolicyCount",
        "exportIntegrationHealthCredentialFreshnessUnknownCount",
        "exportIntegrationHealthCredentialFreshnessStatusCountsSource",
        "exportIntegrationHealthCredentialFreshnessStatusCountsMismatch",
        "exportIntegrationHealthCredentialFreshnessStatusCountsServer",
        "exportIntegrationHealthCredentialFreshnessStatusCountsFallback",
        "exportIntegrationHealthRecommendedCommands",
        "exportSchemaVersion",
        "Export Governance Schema JSON",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_telemetry_export_schema_operator_contract_section():
    content = _runbook_text()
    required_fragments = [
        "Telemetry Export Schema (Operator Contract)",
        "connector-telemetry-summary-*.json",
        "exportRecentEventsFilter=packet",
        "exportRecentEventsSelectedFilter",
        "exportRecentEventsServerFilter",
        "exportRecentEventsServerFilterRaw",
        "exportRecentEventsServerFilterRawTrimmed",
        "exportRecentEventsServerFilterBlank",
        "exportRecentEventsServerFilterUnsupported",
        "exportRecentEventsServerFilterEvaluation",
        "exportRecentEventsServerFilterNormalizationChanged",
        "exportRecentEventsFilterMismatch",
        "exportRecentEventsFilterSource",
        "exportRecentEventsFilterResolution",
        "exportRecentEventsDisplayedCount",
        "exportRecentEventsTotalCount",
        "exportRecentEventsPacketValidationCount",
        "exportRecentEventsNonPacketCount",
        "exportRecentEventsGovernanceStatusCounts",
        "exportRecentEventsPacketValidationStatusCounts",
        "exportConnectorValidationEventCount",
        "exportConnectorValidationLatestEventAt",
        "exportConnectorValidationEndpointCount",
        "exportConnectorValidationProviderCount",
        "exportConnectorValidationFieldCount",
        "exportConnectorValidationReasonCount",
        "exportRetryAuditEventCount",
        "exportRetryAuditLatestEventAt",
        "exportRetryAuditMaxNextDelaySeconds",
        "exportRetryAuditAvgNextDelaySeconds",
        "exportRetryAuditOperationCount",
        "exportRetryAuditProviderCount",
        "exportIntegrationHealthStatus",
        "exportIntegrationHealthGeneratedAt",
        "exportIntegrationHealthHealthyCount",
        "exportIntegrationHealthUnhealthyCount",
        "exportIntegrationHealthActionableUnhealthyProviders",
        "exportIntegrationHealthCredentialActionRequiredProviders",
        "exportIntegrationHealthCredentialConfiguredMaxAgeDays",
        "exportIntegrationHealthCredentialRotationMaxAgeDays",
        "exportIntegrationHealthCredentialFreshnessStatusCounts",
        "exportIntegrationHealthCredentialFreshnessByProvider",
        "exportIntegrationHealthCredentialFreshnessTotalProviders",
        "exportIntegrationHealthCredentialFreshnessActionRequiredCount",
        "exportIntegrationHealthCredentialFreshnessWithinPolicyCount",
        "exportIntegrationHealthCredentialFreshnessUnknownCount",
        "exportIntegrationHealthCredentialFreshnessStatusCountsSource",
        "exportIntegrationHealthCredentialFreshnessStatusCountsMismatch",
        "exportIntegrationHealthCredentialFreshnessStatusCountsServer",
        "exportIntegrationHealthCredentialFreshnessStatusCountsFallback",
        "exportIntegrationHealthRecommendedCommands",
        "exportSchemaVersion",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_traceability_retention_incident_response_section():
    content = _runbook_text()
    required_fragments = [
        "Traceability Snapshot Retention Incident Response",
        "Traceability Snapshot Governance",
        "status is `ACTION_REQUIRED`",
        "npm run verify:telemetry:traceability",
        "npm run verify:telemetry:traceability:cleanup:dry-run",
        "npm run verify:telemetry:traceability:cleanup:policy",
        "npm run verify:telemetry:traceability:cleanup:apply:guarded",
        "npm run verify:governance:weekly",
        "npm run verify:smoke:governance-report",
        "npm run verify:smoke:baseline-governance-drift",
        "npm run verify:smoke:baseline-orchestration-remediation",
        "npm run verify:smoke:traceability-ci-guard",
        "npm run verify:smoke:traceability-governance-handoff",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_baseline_orchestration_remediation_escalation_matrix():
    content = _runbook_text()
    required_fragments = [
        "Baseline Orchestration Remediation Escalation Matrix",
        "Integrations Engineer",
        "Release Manager",
        "QA Engineer",
        "Sales Ops Lead",
        "npm run verify:smoke:baseline-orchestration-remediation",
        "npm run verify:smoke:orchestration-slo-gate",
        "npm run verify:baseline:metrics",
        "npm run verify:smoke:baseline-governance-drift",
        "recommendedCommands",
        "governanceExport.recommendedCommands",
        "recommendedCommands[0]",
        "recommendedCommandCount",
        "governanceExport.recommendedCommandCount",
        "reasonCodeCount",
        "governanceExport.reasonCodeCount",
        "runtimePrereqs.present",
        "runtimePrereqs.available",
        "runtimePrereqs.passed",
        "runtimePrereqs.contractValid",
        "runtimePrereqs.valid",
        "runtimePrereqs.missingCheckCount",
        "governanceExport.runtimePrereqs",
        "totals.runtimePrereqsMissingCheckCount",
        "runtimePrereqsParity.matchesNested",
        "runtimePrereqsCommand",
        "npm run verify:baseline:command-aliases:artifact",
        "npm run verify:baseline:command-aliases:artifact:contract",
        "npm run verify:smoke:baseline-command-aliases-artifact",
        "npm run verify:baseline:runtime-prereqs:artifact",
        "npm run verify:baseline:runtime-prereqs:artifact:contract",
        "npm run verify:smoke:runtime-prereqs-artifact",
        "npm run verify:baseline:metrics:artifact",
        "npm run verify:baseline:metrics:artifact:contract",
        "npm run verify:smoke:baseline-metrics-artifact",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_artifact_paths_and_retention():
    content = _runbook_text()
    required_fragments = [
        "backend/test_reports/baseline_metrics.json",
        "backend/test_reports/sales_baseline_command_aliases.json",
        "backend/test_reports/connector_canary_evidence.json",
        "backend/test_reports/connector_signoff_validation.json",
        "backend/test_reports/connector_release_gate_result.json",
        "backend/test_reports/connector_release_gate_result_hold.json",
        "backend/test_reports/connector_release_gate_result_validation_fail.json",
        "backend/test_reports/connector-telemetry-summary-<timestamp>.json",
        "backend/test_reports/connector-telemetry-summary-snapshot.json",
        "backend/test_reports/connector_governance_weekly_report.json",
        "backend/test_reports/governance_handoff_export.json",
        "backend/test_reports/governance_history_export.json",
        "backend/test_reports/governance_packet_validation.json",
        "Retain artifacts for at least 14 days",
        "Retain traceability audit telemetry snapshots for at least 30 days",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_governance_weekly_report_incident_response_section():
    content = _runbook_text()
    required_fragments = [
        "Governance Weekly Report Incident Response",
        "GET /api/integrations/integrations/telemetry/governance-report",
        "GET /api/integrations/integrations/telemetry/governance-report/export",
        "GET /api/integrations/integrations/telemetry/governance-report/history",
        "npm run verify:governance:weekly:report",
        "npm run verify:governance:weekly:report:contract",
        "npm run verify:governance:weekly:endpoint:contract",
        "npm run verify:governance:packet:fixture",
        "npm run verify:governance:packet:validate",
        "npm run verify:governance:packet:contract",
        "npm run verify:governance:packet:artifact:fixtures",
        "npm run verify:governance:packet:artifact:retention",
        "npm run verify:governance:packet:artifact:cleanup:dry-run",
        "npm run verify:governance:packet:artifact:cleanup:policy",
        "npm run verify:governance:packet:artifact:cleanup:apply:guarded",
        "npm run verify:governance:weekly:retention",
        "npm run verify:governance:weekly:cleanup:dry-run",
        "npm run verify:governance:weekly:cleanup:policy",
        "npm run verify:governance:weekly:cleanup:apply:guarded",
        "npm run verify:smoke:governance-report",
        "npm run verify:smoke:governance-export-guard",
        "npm run verify:smoke:governance-history-retention",
        "npm run verify:smoke:governance-connector-pressure",
        "npm run verify:smoke:governance-packet",
        "reasonCodeCount",
        "recommendedCommandCount",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_governance_packet_fixture_regeneration_incident_response_section():
    content = _runbook_text()
    required_fragments = [
        "Governance Packet Fixture Regeneration Incident Response",
        "npm run verify:governance:weekly:report",
        "npm run verify:governance:weekly:report:contract",
        "npm run verify:governance:packet:fixture",
        "npm run verify:governance:packet:validate",
        "npm run verify:governance:packet:contract",
        "npm run verify:governance:packet:artifact:fixtures",
        "npm run verify:governance:packet:artifact:retention",
        "npm run verify:governance:packet:artifact:cleanup:dry-run",
        "npm run verify:governance:packet:artifact:cleanup:policy",
        "npm run verify:governance:packet:artifact:cleanup:apply:guarded",
        "npm run verify:governance:weekly:endpoint:contract",
        "npm run verify:smoke:governance-packet",
        "npm run verify:smoke:governance-connector-pressure",
        "backend/test_reports/governance_handoff_export.json",
        "backend/test_reports/governance_history_export.json",
        "backend/test_reports/governance_packet_validation.json",
        "GOVERNANCE_PACKET_VALIDATION_MAX_AGE_HOURS",
        "npm run verify:ci:sales:extended",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_includes_governance_weekly_export_packet_handoff_section():
    content = _runbook_text()
    required_fragments = [
        "Governance Weekly Export Packet Handoff",
        "GET /api/integrations/integrations/telemetry/governance-report/export",
        "GET /api/integrations/integrations/telemetry/governance-report/history",
        "npm run verify:governance:packet:fixture",
        "npm run verify:governance:packet:validate",
        "npm run verify:governance:packet:contract",
        "npm run verify:governance:packet:artifact:fixtures",
        "npm run verify:governance:packet:artifact:retention",
        "npm run verify:governance:packet:artifact:cleanup:dry-run",
        "npm run verify:governance:packet:artifact:cleanup:policy",
        "npm run verify:governance:packet:artifact:cleanup:apply:guarded",
        "Export Governance Handoff JSON",
        "exportSchemaVersion",
        "governanceExport.exportSchemaVersion",
        "items[].exportSchemaVersion",
        "handoff/history `exportSchemaVersion` values are consistent",
        "governance report/export/history `status` values must be one of `READY`, `ACTION_REQUIRED`, `PASS`, `FAIL`, `UNKNOWN`",
        "governance handoff/history `governanceExport.status` values must be one of `READY`, `ACTION_REQUIRED`, `PASS`, `FAIL`, `UNKNOWN`",
        "governance history `items[].status` values must be one of `READY`, `ACTION_REQUIRED`, `PASS`, `FAIL`, `UNKNOWN`",
        "governance report `governanceStatusCounts` keys must be canonical status tokens (`READY`, `ACTION_REQUIRED`, `PASS`, `FAIL`, `UNKNOWN`)",
        "governance report `traceabilityDecisionCounts` keys must be canonical decision tokens (`PROCEED`, `HOLD`, `UNKNOWN`)",
        "malformed or punctuation-only governance/decision tokens should collapse to `UNKNOWN`",
        "npm run verify:governance:weekly:report:contract",
        "generated packet artifacts normalize status to canonical `ACTION_REQUIRED`",
        "packet validator accepts normalized status variants (for example `action-required`) but rejects punctuation-only tokens",
        "packet connector endpoint keys in parity checks are normalized (`apollo search` and `apollo-search` collapse to `apollo_search`)",
        "reasonCodeCount == len(reasonCodes)",
        "recommendedCommandCount == len(recommendedCommands)",
        "governanceExport.reasonCodeCount == reasonCodeCount",
        "governanceExport.recommendedCommandCount == recommendedCommandCount",
        "runtimePrereqs.present",
        "runtimePrereqs.available",
        "runtimePrereqs.passed",
        "runtimePrereqs.contractValid",
        "runtimePrereqs.valid",
        "runtimePrereqs.missingCheckCount == len(runtimePrereqs.missingChecks.commands) + len(runtimePrereqs.missingChecks.workspace)",
        "governanceExport.runtimePrereqs == runtimePrereqs",
        "totals.runtimePrereqsMissingCheckCount == runtimePrereqs.missingCheckCount",
        "runtimePrereqsParity.matchesNested",
        "runtimePrereqsCommand",
        "handoff/history `connectorRateLimit.eventCount` equals `governanceExport.connectorRateLimit.eventCount`",
        "handoff/history `connectorRateLimit.byEndpoint` equals `governanceExport.connectorRateLimit.byEndpoint`",
        "handoff/history `connectorRateLimit.pressure.label` equals `governanceExport.connectorRateLimit.pressure.label`",
        "handoff/history `totals.connectorRateLimitEventCount` equals `connectorRateLimit.eventCount`",
        "handoff/history `sendgridWebhookTimestamp.eventCount` equals `governanceExport.sendgridWebhookTimestamp.eventCount`",
        "handoff/history `sendgridWebhookTimestamp.timestampAnomalyCountTotal` equals `governanceExport.sendgridWebhookTimestamp.timestampAnomalyCountTotal`",
        "handoff/history `totals.sendgridWebhookTimestampEventCount` equals `sendgridWebhookTimestamp.eventCount`",
        "handoff/history `totals.sendgridWebhookTimestampAnomalyCountTotal` equals `sendgridWebhookTimestamp.timestampAnomalyCountTotal`",
        "sendgridWebhookTimestampParity.eventCountMatchesNested",
        "sendgridWebhookTimestampParity.eventCountMatchesTotals",
        "sendgridWebhookTimestampParity.anomalyCountTotalMatchesNested",
        "sendgridWebhookTimestampParity.anomalyCountTotalMatchesTotals",
        "backend/test_reports/connector_governance_weekly_report.json",
        "npm run verify:governance:weekly:cleanup:policy",
        "npm run verify:governance:weekly:cleanup:apply:guarded",
        "npm run verify:smoke:governance-export-guard",
        "npm run verify:smoke:governance-history-retention",
        "npm run verify:smoke:governance-connector-pressure",
        "npm run verify:smoke:governance-packet",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_integrations_reliability_runbook_documents_sales_smoke_chain_stage_expansion():
    content = _runbook_text()
    required_fragments = [
        "Combined sales smoke chain stages include `verify:smoke:sales-dashboard` immediately after `verify:smoke:frontend-sales`, `verify:smoke:multi-channel-controls` before `verify:smoke:baseline-command-aliases`, `verify:smoke:baseline-command-aliases` before `verify:smoke:baseline-command-aliases-artifact`, `verify:smoke:baseline-command-aliases-artifact` before `verify:smoke:campaign`, `verify:smoke:runtime-prereqs-artifact` before `verify:smoke:baseline-metrics-artifact`, and include `verify:smoke:connector-reliability` + `verify:smoke:telemetry-quality` between credential lifecycle and telemetry event-root backfill gates.",
        "`verify:smoke:connector-reliability` runs after `verify:smoke:credential-lifecycle` and executes `verify:smoke:connector-orchestration`, `verify:smoke:connector-provider-lookups`, `verify:smoke:connector-lookups`, `verify:smoke:sendgrid-reliability`, and `verify:smoke:credential-freshness`.",
        "`verify:smoke:telemetry-quality` runs `verify:smoke:telemetry-status-filter`, `verify:smoke:telemetry-status-counts`, and `verify:smoke:telemetry-export-distribution`.",
        "`verify:smoke:connector-lookups` wrapper executes immediately after `verify:smoke:connector-provider-lookups` and runs `verify:smoke:connector-lookups-ui` followed by `verify:smoke:connector-lookups-export`.",
    ]
    for fragment in required_fragments:
        assert fragment in content
