from pathlib import Path


DEV_SETUP_PATH = Path(__file__).resolve().parents[2] / "DEV_SETUP.md"


def _content() -> str:
    return DEV_SETUP_PATH.read_text(encoding="utf-8")


def test_dev_setup_exists():
    assert DEV_SETUP_PATH.exists()


def test_dev_setup_includes_required_sales_verification_commands():
    content = _content()
    required_fragments = [
        "npm run test",
        "npm run lint",
        "npm run typecheck",
        "npm run verify:baseline:runtime-prereqs",
        "npm run verify:baseline:command-aliases",
        "npm run verify:baseline:command-aliases:artifact",
        "npm run verify:baseline:command-aliases:artifact:contract",
        "npm run verify:baseline:command-aliases:artifact:retention",
        "npm run verify:baseline:command-aliases:artifact:fixtures",
        "npm run verify:baseline:command-aliases:artifact:cleanup:dry-run",
        "npm run verify:baseline:command-aliases:artifact:cleanup:policy",
        "npm run verify:baseline:command-aliases:artifact:cleanup:apply:guarded",
        "npm run verify:baseline:runtime-prereqs:artifact",
        "npm run verify:baseline:runtime-prereqs:artifact:contract",
        "npm run verify:baseline:runtime-prereqs:artifact:retention",
        "npm run verify:baseline:runtime-prereqs:artifact:fixtures",
        "npm run verify:baseline:runtime-prereqs:artifact:cleanup:dry-run",
        "npm run verify:baseline:runtime-prereqs:artifact:cleanup:policy",
        "npm run verify:baseline:runtime-prereqs:artifact:cleanup:apply:guarded",
        "npm run verify:baseline",
        "npm run verify:baseline:metrics",
        "npm run verify:baseline:metrics:artifact",
        "npm run verify:baseline:metrics:artifact:contract",
        "npm run verify:baseline:metrics:artifact:retention",
        "npm run verify:baseline:metrics:artifact:fixtures",
        "npm run verify:baseline:metrics:artifact:cleanup:dry-run",
        "npm run verify:baseline:metrics:artifact:cleanup:policy",
        "npm run verify:baseline:metrics:artifact:cleanup:apply:guarded",
        "npm run verify:baseline:metrics:contract",
        "npm run verify:ci:sales",
        "npm run verify:backend:sales:integrations",
        "npm run verify:auth:integrations:contracts",
        "npm run verify:docs:sales:connectors",
        "npm run verify:docs:sales",
        "npm run verify:release-gate:artifact:contract",
        "npm run verify:release-gate:artifact:fixtures",
        "npm run verify:release-gate:artifact:retention",
        "npm run verify:release-gate:artifact:cleanup:dry-run",
        "npm run verify:release-gate:artifact:cleanup:policy",
        "npm run verify:release-gate:artifact:cleanup:apply:guarded",
        "npm run verify:telemetry:traceability:fixture",
        "npm run verify:telemetry:traceability:contract",
        "npm run verify:telemetry:traceability:retention",
        "npm run verify:telemetry:traceability:cleanup:dry-run",
        "npm run verify:telemetry:traceability:cleanup:policy",
        "npm run verify:telemetry:traceability:cleanup:apply:guarded",
        "npm run verify:telemetry:event-root:backfill:dry-run",
        "npm run verify:telemetry:event-root:backfill:policy",
        "npm run verify:telemetry:event-root:backfill:apply:guarded",
        "npm run verify:telemetry:event-root:backfill:artifact:contract",
        "npm run verify:telemetry:event-root:backfill:artifact:fixtures",
        "npm run verify:telemetry:event-root:backfill:artifact:retention",
        "npm run verify:telemetry:event-root:backfill:artifact:cleanup:dry-run",
        "npm run verify:telemetry:event-root:backfill:artifact:cleanup:policy",
        "npm run verify:telemetry:event-root:backfill:artifact:cleanup:apply:guarded",
        "npm run verify:telemetry:traceability",
        "npm run verify:governance:weekly:report",
        "npm run verify:governance:weekly:report:contract",
        "npm run verify:governance:weekly:endpoint:contract",
        "npm run verify:governance:packet:fixture",
        "npm run verify:governance:packet:validate",
        "npm run verify:governance:packet:contract",
        "npm run verify:governance:packet:artifact:fixtures",
        "npm run verify:governance:packet:artifact:retention",
        "npm run verify:governance:packet:artifact:cleanup:dry-run",
        "npm run verify:governance:packet:artifact:cleanup:policy",
        "npm run verify:governance:packet:artifact:cleanup:apply:guarded",
        "npm run verify:governance:schema:preflight",
        "npm run verify:governance:weekly:retention",
        "npm run verify:governance:weekly:cleanup:dry-run",
        "npm run verify:governance:weekly:cleanup:policy",
        "npm run verify:governance:weekly:cleanup:apply:guarded",
        "npm run verify:governance:weekly",
        "npm run verify:smoke:governance-report",
        "npm run verify:smoke:governance-export-guard",
        "npm run verify:smoke:governance-history-retention",
        "npm run verify:smoke:governance-packet",
        "npm run verify:smoke:governance-connector-pressure",
        "npm run verify:smoke:governance-duplicate-artifact-remediation",
        "npm run verify:smoke:governance-schema-endpoint",
        "npm run verify:smoke:governance-schema-ui",
        "npm run verify:smoke:baseline-command-aliases-artifact",
        "npm run verify:smoke:runtime-prereqs-artifact",
        "npm run verify:smoke:baseline-metrics-artifact",
        "npm run verify:smoke:telemetry-packet-filter",
        "npm run verify:smoke:telemetry-status-filter",
        "npm run verify:smoke:telemetry-status-counts",
        "Telemetry status-count provenance matrix verification:",
        "recentEventsGovernanceStatusCountsSource",
        "recentEventsPacketValidationStatusCountsSource",
        "recentEventsGovernanceStatusCountsMismatch",
        "recentEventsPacketValidationStatusCountsMismatch",
        "recentEventsGovernanceStatusCountsServer",
        "recentEventsPacketValidationStatusCountsServer",
        "recentEventsGovernanceStatusCountsFallback",
        "recentEventsPacketValidationStatusCountsFallback",
        "recentEventsGovernanceStatusCountsPosture",
        "recentEventsPacketValidationStatusCountsPosture",
        "recentEventsGovernanceStatusCountsPostureSeverity",
        "recentEventsPacketValidationStatusCountsPostureSeverity",
        "recentEventsGovernanceStatusCountsRequiresInvestigation",
        "recentEventsPacketValidationStatusCountsRequiresInvestigation",
        "when backend posture tokens are invalid/unsupported, UI/export posture metadata must fall back to computed source+mismatch posture defaults.",
        "exportRecentEventsGovernanceStatusCountsPosture",
        "exportRecentEventsPacketValidationStatusCountsPosture",
        "exportRecentEventsGovernanceStatusCountsPostureSeverity",
        "exportRecentEventsPacketValidationStatusCountsPostureSeverity",
        "exportRecentEventsGovernanceStatusCountsRequiresInvestigation",
        "exportRecentEventsPacketValidationStatusCountsRequiresInvestigation",
        "source=server, mismatch=false",
        "source=server, mismatch=true",
        "source=local, mismatch=false",
        "source=local, mismatch=true",
        "npm run verify:smoke:telemetry-event-root-backfill",
        "npm run verify:smoke:telemetry-event-root-backfill-artifact-cleanup",
        "npm run verify:smoke:telemetry-export-distribution",
        "npm run verify:smoke:frontend-sales",
        "npm run verify:smoke:multi-channel-controls",
        "npm run verify:smoke:baseline-command-aliases",
        "npm run verify:smoke:traceability-ci-guard",
        "npm run verify:smoke:traceability-governance-handoff",
        "npm run verify:smoke:baseline-governance-drift",
        "npm run verify:smoke:baseline-orchestration-remediation",
        "recommendedCommands",
        "governanceExport.recommendedCommands",
        "runtimePrereqs.present",
        "runtimePrereqs.available",
        "runtimePrereqs.passed",
        "runtimePrereqs.contractValid",
        "runtimePrereqs.valid",
        "runtimePrereqs.missingCheckCount",
        "governanceExport.runtimePrereqs",
        "totals.runtimePrereqsMissingCheckCount",
        "runtimePrereqsParity.matchesNested",
        "runtimePrereqsCommand",
        "npm run verify:ci:sales:extended",
        "npm run verify:smoke:canary-dry-run",
        "npm run verify:smoke:credential-lifecycle",
        "npm run verify:smoke:connector-reliability",
        "npm run verify:smoke:connector-orchestration",
        "npm run verify:smoke:connector-provider-lookups",
        "npm run verify:smoke:connector-lookups",
        "npm run verify:smoke:connector-lookups-ui",
        "npm run verify:smoke:connector-lookups-export",
        "npm run verify:smoke:sendgrid-reliability",
        "npm run verify:smoke:credential-freshness",
        "npm run verify:smoke:telemetry-quality",
        "npm run verify:smoke:sales",
        "npm run verify:smoke:sales-dashboard",
        "npm run verify:smoke:workflow-contracts",
        "Combined sales smoke chain (frontend-sales + sales-dashboard + multi-channel controls + baseline command aliases + baseline command-alias artifact + campaign + runtime-prereq artifact + baseline metrics artifact + canary dry-run + credential lifecycle + connector reliability + telemetry quality + telemetry event-root backfill + telemetry event-root fixture cleanup + schema gate + orchestration SLO gate + release gate + health)",
        "npm run verify:smoke:schema-gate",
        "npm run verify:smoke:orchestration-slo-gate",
        "npm run verify:smoke:release-gate",
        "npm run verify:baseline:quick",
        "backend/test_reports/baseline_metrics.json",
        "backend/test_reports/sales_baseline_command_aliases.json",
        "backend/test_reports/sales_runtime_prereqs.json",
        "backend/test_reports/connector-telemetry-summary-snapshot.json",
        "backend/test_reports/connector_governance_weekly_report.json",
        "backend/test_reports/governance_handoff_export.json",
        "backend/test_reports/governance_history_export.json",
        "backend/test_reports/governance_packet_validation.json",
        "GOVERNANCE_PACKET_VALIDATION_MAX_AGE_HOURS",
        "BACKFILL_ALLOW_APPLY",
        "BACKFILL_ARTIFACT_CLEANUP_ALLOW_APPLY",
        "BASELINE_COMMAND_ALIASES_ARTIFACT_CLEANUP_ALLOW_APPLY",
        "RUNTIME_PREREQS_ARTIFACT_CLEANUP_ALLOW_APPLY",
        "BASELINE_METRICS_ARTIFACT_CLEANUP_ALLOW_APPLY",
        "RELEASE_GATE_ARTIFACT_CLEANUP_ALLOW_APPLY",
        "GOVERNANCE_PACKET_ARTIFACT_CLEANUP_ALLOW_APPLY",
    ]
    for fragment in required_fragments:
        assert fragment in content


def test_dev_setup_includes_schema_threshold_slo_script_examples():
    content = _content()
    required_fragments = [
        "collect_connector_canary_evidence.py",
        "evaluate_connector_slo_gates.py",
        "--min-schema-v2-pct 95",
        "--min-schema-v2-sample-count 25",
        "--max-orchestration-attempt-error-count 5",
        "--max-orchestration-attempt-skipped-count 25",
    ]
    for fragment in required_fragments:
        assert fragment in content
